Added MapToCurve interface
algorand/pairing-plus pull request #20
Opened 2021-08-06 07:00 UTC by nikhilvanjani

2021-08-06 07:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/pairing-plus?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/pairing-plus?pullRequest=20) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/pairing-plus?pullRequest=20) it.</sub>

2021-08-11 22:05 UTC, kwantam requested changes
The most significant bit is that this looks good! :+1:

But I think maybe Clippy suggested some changes that should be rolled back, and there's a small bit of cleanup to do here and there. See inline comments.

2021-08-11 22:05 UTC, kwantam commented on src/map_to_curve.rs
> +}
```suggestion
}
```

(nice to have a trailing newline imo)

2021-08-12 13:25 UTC, nikhilvanjani commented on src/lib.rs
> +    fn into_affine(self) -> Result<Self::Affine, GroupDecodingError>;
Yes, this was in response to clippy warnings. Sure, I will make the breaking change.

2021-08-12 13:50 UTC, nikhilvanjani commented on src/lib.rs
> +    fn into_affine(self) -> Result<Self::Affine, GroupDecodingError>;
the following was the error. Not sure, what must I allow in this case.

error: methods called `into_*` usually take `self` by value
   --> src/lib.rs:211:20
    |
211 |     fn into_affine(&self) -> Self::Affine;
    |                    ^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:4:44
    |
4   | #![cfg_attr(feature = "cargo-clippy", deny(warnings))]
    |                                            ^^^^^^^^
    = note: `#[deny(clippy::wrong_self_convention)]` implied by `#[deny(warnings)]`
    = help: consider choosing a less ambiguous name
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention

2021-08-12 13:56 UTC, nikhilvanjani commented on src/lib.rs
> +            _ => write!(f, "{:?}", self),
Yes the following clippy warning -
====
error: using `to_string` in `fmt::Display` implementation might lead to infinite recursion
   --> src/lib.rs:423:34
    |
423 |             _ => write!(f, "{}", self.to_string()),
    |                                  ^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::to_string_in_display)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_display
====
I tried to follow suggestions from the last help link above and it suggested to do `write!(f, "{}", self.0)`. But this resulted in the error `error[E0609]: no field `0` on type `&GroupDecodingError``. So, I moved to `write!(f, "{:?}", self)`. I can do something else if there's any suggestion.

2021-08-12 13:58 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +	fn map_two_field_elements_to_curve(p1: &PtT::Base, p2: &PtT::Base) -> PtT;
Sure, I can change this.

2021-08-12 14:16 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +use bls12_381::{ClearH, IsogenyMap, OSSWUMap};
done.

2021-08-12 14:16 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +        println!("map_two_field_elements_to_curve called");
done.

2021-08-12 14:16 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +        println!("map_one_field_element_to_curve called");
done.

2021-08-12 14:16 UTC, nikhilvanjani commented on src/hash_to_curve.rs
> +        // p
done.

2021-08-12 14:17 UTC, nikhilvanjani commented on src/hash_to_curve.rs
> +        // p
done.

2021-08-12 14:19 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +}
done.

2021-08-12 14:24 UTC, nikhilvanjani commented on src/map_to_curve.rs
> +        p
Sounds reasonable to do. An optimization could be-
`debug_assert!(p.into_affine().in_subgroup());`
based on the following code in g1.rs:319:
`
    impl SubgroupCheck for G1Affine {
        fn in_subgroup(&self) -> bool {
            self.is_on_curve() && self.is_in_correct_subgroup_assuming_on_curve()
        }
    }
`

2021-08-12 16:45 UTC, kwantam commented on src/lib.rs
> +    fn into_affine(self) -> Result<Self::Affine, GroupDecodingError>;
:+1:

2021-08-12 16:46 UTC, kwantam commented on src/lib.rs
> +            _ => write!(f, "{:?}", self),
Got it. Seems OK then.

2021-08-12 16:47 UTC, kwantam commented on src/map_to_curve.rs
> +        p
Excellent, that sounds exactly right.

2021-08-12 16:47 UTC, kwantam commented on src/map_to_curve.rs
> +        p
So I guess the new version would be:

```suggestion
        debug_assert!(p.into_affine().in_subgroup());
        p
```

right?

2021-08-12 16:48 UTC, kwantam commented on src/map_to_curve.rs
> +        p
As above,

```suggestion
        debug_assert!(p.into_affine().in_subgroup());
        p
```

2021-08-12 16:52 UTC, kwantam commented on src/lib.rs
> +    fn into_affine(self) -> Result<Self::Affine, GroupDecodingError>;
The fix is to make the declaration the following:

```
        #[allow(clippy::wrong_self_convention)]
        fn into_affine(&self) -> Result<Self::Affine, GroupDecodingError>;
```

2021-08-12 16:54 UTC, kwantam commented on src/lib.rs
> +    fn into_affine_unchecked(self) -> Result<Self::Affine, GroupDecodingError>;
Also here:

```rust
        #[allow(clippy::wrong_self_convention)]
        fn into_affine_unchecked(&self) -> Result<Self::Affine, GroupDecodingError>;
```

2021-08-12 16:54 UTC, kwantam requested changes
Cool! A couple further comments. Adding the `#[allow(...)]`s will make the tests pass.

2021-08-12 17:55 UTC, nikhilvanjani commented on src/lib.rs
> +    fn into_affine_unchecked(self) -> Result<Self::Affine, GroupDecodingError>;
done.

2021-08-12 18:34 UTC, kwantam commented on src/lib.rs
> +
:+1:

2021-08-12 18:34 UTC, kwantam commented on src/lib.rs
> +    fn into_affine_unchecked(self) -> Result<Self::Affine, GroupDecodingError>;
:+1:

2021-08-12 18:36 UTC, kwantam approved these changes
Looks good to me! One last `cargo fmt` and `cargo clippy`, maybe?

2021-08-12 20:51 UTC, merged